filecode = 
{'00': [{'dir': 'files1/', 'disppage': '', 'pagenum': '005', 'sfx': 'png', 'word': 'title page'}, {'dir': 'files1/', 'disppage': '', 'pagenum': '006', 'sfx': 'png', 'word': 'publisher'}, {'dir': 'files1/', 'disppage': '', 'pagenum': '007', 'sfx': 'png', 'word': 'Preface'}, {'dir': 'files1/', 'disppage': '', 'pagenum': '008', 'sfx': 'png', 'word': ''}, {'dir': 'files1/', 'disppage': '', 'pagenum': '009', 'sfx': 'png', 'word': ''}, {'dir': 'files1/', 'disppage': '', 'pagenum': '010', 'sfx': 'png', 'word': ''}, {'dir': 'files1/', 'disppage': '', 'pagenum': '011', 'sfx': 'png', 'word': 'Table of contents'}, {'dir': 'files1/', 'disppage': '', 'pagenum': '012', 'sfx': 'png', 'word': ''}, {'dir': 'files1/', 'disppage': '', 'pagenum': '013', 'sfx': 'png', 'word': ''}, {'dir': 'files1/', 'disppage': '', 'pagenum': '014', 'sfx': 'png', 'word': 'Abbreviations'}],
 '01': [{'dir': 'files1/', 'disppage': 1, 'pagenum': '015', 'sfx': 'png', 'word': 'I: Alphabet, &sect; 1.'},
        {'dir': 'files1/', 'disppage': 2, 'pagenum': '016', 'sfx': 'png', 'word': '&sect; 2. Devanagari alphabet'},
        {'dir': 'files1/', 'disppage': 3, 'pagenum': '017', 'sfx': 'png', 'word': '&sect; 3. Vowels'},
        {'dir': 'files1/', 'disppage': 4, 'pagenum': '018', 'sfx': 'png', 'word': '&sect; 4. Consonants'},
        {'dir': 'files1/', 'disppage': 5, 'pagenum': '019', 'sfx': 'png', 'word': '&sect; 5. Soft/hard consonants'},
        {'dir': 'files1/', 'disppage': 5, 'pagenum': '019', 'sfx': 'png', 'word': '&sect; 6. Other Sanskrit sounds'},
        {'dir': 'files1/', 'disppage': 6, 'pagenum': '020', 'sfx': 'png', 'word': '&sect; 7. Aspirates and unaspirates'},
        {'dir': 'files1/', 'disppage': 6, 'pagenum': '020', 'sfx': 'png', 'word': '&sect; 8. Alphabet table'},
        {'dir': 'files1/', 'disppage': 7, 'pagenum': '021', 'sfx': 'png', 'word': '&sect; 9. savarna letters'},
        {'dir': 'files1/', 'disppage': 7, 'pagenum': '021', 'sfx': 'png', 'word': '&sect; 10. svara, vyanjana'},
        {'dir': 'files1/', 'disppage': 8, 'pagenum': '022', 'sfx': 'png', 'word': '&sect; 11. syllable'},
        {'dir': 'files1/', 'disppage': 8, 'pagenum': '022', 'sfx': 'png', 'word': '&sect; 12. vowel signs'},
        {'dir': 'files1/', 'disppage': 8, 'pagenum': '022', 'sfx': 'png', 'word': '&sect; 12. compound consonants'},
        {'dir': 'files1/', 'disppage': 10, 'pagenum': '024', 'sfx': 'png', 'word': '&sect; 13. punctuation'},
        {'dir': 'files1/', 'disppage': 10, 'pagenum': '024', 'sfx': 'png', 'word': '&sect; 13. avagraha'},
        {'dir': 'files1/', 'disppage': 10, 'pagenum': '024', 'sfx': 'png', 'word': '&sect; 14. prosodially long vowel'},
        {'dir': 'files1/', 'disppage': 10, 'pagenum': '024', 'sfx': 'png', 'word': '&sect; 15. guna and vrddhi'},
        {'dir': 'files1/', 'disppage': 11, 'pagenum': '025', 'sfx': 'png', 'word': '&sect; 16. semivowels'},
        {'dir': 'files1/', 'disppage': 11, 'pagenum': '025', 'sfx': 'png', 'word': '&sect; 17. numerical figures'}],
 '02': [{'dir': 'files1/', 'disppage': 12, 'pagenum': '026', 'sfx': 'png', 'word': 'II. Rules of Sandhi'},
        {'dir': 'files1/', 'disppage': 12, 'pagenum': '026', 'sfx': 'png', 'word': '<span class="section">Svara-sandhi</span>'},
        {'dir': 'files1/', 'disppage': 12, 'pagenum': '026', 'sfx': 'png', 'word': '&sect; 19 similar simple vowels'},
        {'dir': 'files1/', 'disppage': 13, 'pagenum': '027', 'sfx': 'png', 'word': '&sect; 20 <span class="san">a</span> + simple vowel'},
        {'dir': 'files1/', 'disppage': 14, 'pagenum': '028', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 15, 'pagenum': '029', 'sfx': 'png', 'word': '&sect; 21 <span class="san">a</span> plus diphthong'},
        {'dir': 'files1/', 'disppage': 16, 'pagenum': '030', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 17, 'pagenum': '031', 'sfx': 'png', 'word': '&sect; 22 <span class="san">i</span> plus vowel'},
        {'dir': 'files1/', 'disppage': 18, 'pagenum': '032', 'sfx': 'png', 'word': '&sect; 23 <span class="san">i</span> plus vowel (optional) '},
        {'dir': 'files1/', 'disppage': 19, 'pagenum': '033', 'sfx': 'png', 'word': '&sect; 24 diphthong plus vowel'},
        {'dir': 'files1/', 'disppage': 20, 'pagenum': '034', 'sfx': 'png', 'word': '&sect; 25 diphthong plus <span class="san">a</span>'},
        {'dir': 'files1/', 'disppage': 20, 'pagenum': '034', 'sfx': 'png', 'word': '&sect; 26 sandhi exceptions, <span class="san">pragfhya</span>'},
        {'dir': 'files1/', 'disppage': 21, 'pagenum': '035', 'sfx': 'png', 'word': 'sandhi exceptions, pluta vowels'},
        {'dir': 'files1/', 'disppage': 22, 'pagenum': '036', 'sfx': 'png', 'word': '&sect; 27. particle <span class="san">u</span>'},
        {'dir': 'files1/', 'disppage': 22, 'pagenum': '036', 'sfx': 'png', 'word': '<span class="section">Hal-sandhi</span>. &sect; 28. dental'},
        {'dir': 'files1/', 'disppage': 23, 'pagenum': '037', 'sfx': 'png', 'word': '&sect; 29. dental plus cerebral sibilant'},
        {'dir': 'files1/', 'disppage': 23, 'pagenum': '037', 'sfx': 'png', 'word': '&sect; 30. consonant plus nasal'},
        {'dir': 'files1/', 'disppage': 23, 'pagenum': '037', 'sfx': 'png', 'word': '&sect; 31. dental plus <span class="san">l</span>'},
        {'dir': 'files1/', 'disppage': 24, 'pagenum': '038', 'sfx': 'png', 'word': '&sect; 32. <span class="san">ud</span> plus <span class="san">sTA</span>'},
        {'dir': 'files1/', 'disppage': 24, 'pagenum': '038', 'sfx': 'png', 'word': '&sect; 33. consonant plus <span class="san">h</span>'},
        {'dir': 'files1/', 'disppage': 24, 'pagenum': '038', 'sfx': 'png', 'word': '&sect; 34. consonant plus hard consonant'},
        {'dir': 'files1/', 'disppage': 24, 'pagenum': '038', 'sfx': 'png', 'word': '&sect; 35. consonant plus <span class="san">S</span>'},
        {'dir': 'files1/', 'disppage': 24, 'pagenum': '038', 'sfx': 'png', 'word': '&sect; 36. <span class="san">m</span> at end of word'},
        {'dir': 'files1/', 'disppage': 25, 'pagenum': '039', 'sfx': 'png', 'word': '&sect; 37. anusvara plus consonant'},
        {'dir': 'files1/', 'disppage': 25, 'pagenum': '039', 'sfx': 'png', 'word': '&sect; 38. <span class="san">N</span> or <span class="san">R</span> plus sibilant'},
        {'dir': 'files1/', 'disppage': 26, 'pagenum': '040', 'sfx': 'png', 'word': '&sect; 38. <span class="san">N</span> or <span class="san">n</span> plus sibilant or vowel'},
        {'dir': 'files1/', 'disppage': 26, 'pagenum': '040', 'sfx': 'png', 'word': '&sect; 40. <span class="san">n</span> plus <span class="san">S</span>'},
        {'dir': 'files1/', 'disppage': 26, 'pagenum': '040', 'sfx': 'png', 'word': '&sect; 41. <span class="san">n</span>  -> <span class="san">R</span>'},
        {'dir': 'files1/', 'disppage': 27, 'pagenum': '041', 'sfx': 'png', 'word': '&sect; 42. <span class="san">s</span>  -> <span class="san">z</span>'},
        {'dir': 'files1/', 'disppage': 27, 'pagenum': '041', 'sfx': 'png', 'word': '&sect; 43. <span class="san">m</span>'},
        {'dir': 'files1/', 'disppage': 28, 'pagenum': '042', 'sfx': 'png', 'word': '&sect; 44. insert <span class="san">c</span> before <span class="san">C</span>'},
        {'dir': 'files1/', 'disppage': 28, 'pagenum': '042', 'sfx': 'png', 'word': '<span class="section">Visarga-sandhi</span>.  &sect; 45. <span class="san">s</span>  -> <span class="san">H</span>'},
        {'dir': 'files1/', 'disppage': 29, 'pagenum': '043', 'sfx': 'png', 'word': '&sect; 46. <span class="san">H</span> -> <span class="san">s</span>'},
        {'dir': 'files1/', 'disppage': 31, 'pagenum': '045', 'sfx': 'png', 'word': '&sect; 47. <span class="san">aH</span> -> <span class="san">o</span>'},
        {'dir': 'files1/', 'disppage': 31, 'pagenum': '045', 'sfx': 'png', 'word': '&sect; 48. <span class="san">AH</span> -> <span class="san">A</span>'},
        {'dir': 'files1/', 'disppage': 31, 'pagenum': '045', 'sfx': 'png', 'word': '&sect; 49. vowel plus <span class="san">H</span> -> vowel plus <span class="san">r</span>'},
        {'dir': 'files1/', 'disppage': 32, 'pagenum': '046', 'sfx': 'png', 'word': '&sect; 50. <span class="san">saH</span> -><span class="san">sa</span>'}],
 '03': [{'dir': 'files1/', 'disppage': 32, 'pagenum': '046', 'sfx': 'png', 'word': 'III. Declension of nouns'},
        {'dir': 'files1/', 'disppage': 33, 'pagenum': '047', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 34, 'pagenum': '048', 'sfx': 'png', 'word': '&sect; 57. Normal case terminations'},
        {'dir': 'files1/', 'disppage': 34, 'pagenum': '048', 'sfx': 'png', 'word': '<span class="section">Bases ending in vowels</span>'},
        {'dir': 'files1/', 'disppage': 35, 'pagenum': '049', 'sfx': 'png', 'word': '&sect; 61. Nouns in  <span class="san">a</span>.  <span class="san">rAma</span>  <span class="san">jYAna</span>'},
        {'dir': 'files1/', 'disppage': 35, 'pagenum': '049', 'sfx': 'png', 'word': '&sect; 63. Nouns in <span class="san">A</span>.  <span class="san">gopA</span>'},
        {'dir': 'files1/', 'disppage': 36, 'pagenum': '050', 'sfx': 'png', 'word': '&sect; 65. <span class="san">ramA</span>'},
        {'dir': 'files1/', 'disppage': 37, 'pagenum': '051', 'sfx': 'png', 'word': '&sect; 69. Nouns in  <span class="san">i</span> and <span class="san">u</span>.  <span class="san">hari</span>  <span class="san">mati</span>  <span class="san">guru</span>'},
        {'dir': 'files1/', 'disppage': 38, 'pagenum': '052', 'sfx': 'png', 'word': '<span class="san">Denu</span> <span class="san">vAri</span> '},
        {'dir': 'files1/', 'disppage': 39, 'pagenum': '053', 'sfx': 'png', 'word': '<span class="san">maDu</span> '},
        {'dir': 'files1/', 'disppage': 39, 'pagenum': '053', 'sfx': 'png', 'word': '&sect; 70. <span class="san">Suci</span> <span class="san">guru</span> '},
        {'dir': 'files1/', 'disppage': 40, 'pagenum': '054', 'sfx': 'png', 'word': '&sect; 72. Irregular bases. <span class="san">saKi</span> <span class="san">pati</span>'},
        {'dir': 'files1/', 'disppage': 41, 'pagenum': '055', 'sfx': 'png', 'word': '&sect; 75. Words in  <span class="san">I</span> and <span class="san">U</span>. <span class="san">nadI</span>'},
        {'dir': 'files1/', 'disppage': 42, 'pagenum': '056', 'sfx': 'png', 'word': '<span class="san">vaDU</span>'},
        {'dir': 'files1/', 'disppage': 42, 'pagenum': '056', 'sfx': 'png', 'word': '&sect; 76. Mas. nouns in <span class="san">I</span>. <span class="san">vAtapramI</span>'},
        {'dir': 'files1/', 'disppage': 43, 'pagenum': '057', 'sfx': 'png', 'word': '&sect; 77. Root nouns in <span class="san">I</span> and <span class="san">U</span>.  <span class="san">DI</span> and <span class="san">BU</span>.'},
        {'dir': 'files1/', 'disppage': 44, 'pagenum': '058', 'sfx': 'png', 'word': '<span class="san">praDI</span> and <span class="san">KalapU</span>.'},
        {'dir': 'files1/', 'disppage': 45, 'pagenum': '059', 'sfx': 'png', 'word': '<span class="san">praDI</span>'},
        {'dir': 'files1/', 'disppage': 46, 'pagenum': '060', 'sfx': 'png', 'word': '<span class="san">suDI</span> <span class="san">svaBU</span>'},
        {'dir': 'files1/', 'disppage': 46, 'pagenum': '060', 'sfx': 'png', 'word': '<span class="san">suDi</span>'},
        {'dir': 'files1/', 'disppage': 47, 'pagenum': '061', 'sfx': 'png', 'word': '<span class="san">varzABU</span> &sect; 78. <span class="san">saKI</span>'},
        {'dir': 'files1/', 'disppage': 48, 'pagenum': '062', 'sfx': 'png', 'word': '&sect; 79. <span class="san">strI</span> <span class="san">atistri</span>'},
        {'dir': 'files1/', 'disppage': 48, 'pagenum': '062', 'sfx': 'png', 'word': '&sect; 80. <span class="san">hUhU</span>'},
        {'dir': 'files1/', 'disppage': 49, 'pagenum': '063', 'sfx': 'png', 'word': '&sect; 81. Nouns in  <span class="san">f</span>.  <span class="san">DAtf</span>'},
        {'dir': 'files1/', 'disppage': 50, 'pagenum': '064', 'sfx': 'png', 'word': '&sect; 82. <span class="san">pitf</span>  <span class="san">mAtf</span>'},
        {'dir': 'files1/', 'disppage': 50, 'pagenum': '064', 'sfx': 'png', 'word': '&sect; 83.  <span class="san">krozwu</span>'},
        {'dir': 'files1/', 'disppage': 51, 'pagenum': '065', 'sfx': 'png', 'word': '&sect; 84. Words in <span class="san">F</span> and <span class="san">x</span>'},
        {'dir': 'files1/', 'disppage': 52, 'pagenum': '066', 'sfx': 'png', 'word': '&sect; 85. Words in <span class="san">e</span> and <span class="san">E</span>.  <span class="san">se</span> and <span class="san">rE</span> '},
        {'dir': 'files1/', 'disppage': 53, 'pagenum': '067', 'sfx': 'png', 'word': '&sect; 85. Words in <span class="san">o</span> and <span class="san">O</span>.  <span class="san">go</span> and <span class="san">glO</span> '},
        {'dir': 'files1/', 'disppage': 54, 'pagenum': '068', 'sfx': 'png', 'word': '<span class="section">Bases ending in consonants</span>'},
        {'dir': 'files1/', 'disppage': 54, 'pagenum': '068', 'sfx': 'png', 'word': '&sect; 88. Bases in <span class="san">r</span>, <span class="san">l</span>, <span class="san">R</span>. <span class="san">kamal</span>'},
        {'dir': 'files1/', 'disppage': 55, 'pagenum': '069', 'sfx': 'png', 'word': '&sect; 90. Bases in <span class="san">k</span>,<span class="san">g</span>,<span class="san">w</span>,<span class="san">q</span>,<span class="san">t</span>,<span class="san">d</span>,<span class="san">p</span>,<span class="san">b</span>'},
        {'dir': 'files1/', 'disppage': 55, 'pagenum': '069', 'sfx': 'png', 'word': '&sect; 92. <span class="san">samiD</span>'},
        {'dir': 'files1/', 'disppage': 56, 'pagenum': '070', 'sfx': 'png', 'word': '<span class="san">sarvak</span>, etc'},
        {'dir': 'files1/', 'disppage': 56, 'pagenum': '070', 'sfx': 'png', 'word': '&sect; 93. Bases in <span class="san">c</span>,<span class="san">j</span>,<span class="san">S</span>,<span class="san">z</span>,<span class="san">h</span>'},
        {'dir': 'files1/', 'disppage': 57, 'pagenum': '071', 'sfx': 'png', 'word': '&sect; 93. <span class="san">vAc</span> <span class="san">rAj</span>'},
        {'dir': 'files1/', 'disppage': 58, 'pagenum': '072', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 59, 'pagenum': '073', 'sfx': 'png', 'word': '<span class="san">muh</span>'},
        {'dir': 'files1/', 'disppage': 60, 'pagenum': '074', 'sfx': 'png', 'word': '&sect; 98. Irregular bases. <span class="san">turAsAh</span> '},
        {'dir': 'files1/', 'disppage': 60, 'pagenum': '074', 'sfx': 'png', 'word': '&sect; 99. <span class="san">viSvarAw</span> '},
        {'dir': 'files1/', 'disppage': 60, 'pagenum': '074', 'sfx': 'png', 'word': '&sect; 100. Root nouns in <span class="san">vAh</span> '},
        {'dir': 'files1/', 'disppage': 61, 'pagenum': '075', 'sfx': 'png', 'word': '&sect; 101. <span class="san">upAnah</span>'},
        {'dir': 'files1/', 'disppage': 61, 'pagenum': '075', 'sfx': 'png', 'word': '&sect; 102. <span class="san">anaquh</span>'},
        {'dir': 'files1/', 'disppage': 61, 'pagenum': '075', 'sfx': 'png', 'word': '&sect; 103. <span class="san">avayAj</span>, <span class="san">puroqAS</span>'},
        {'dir': 'files1/', 'disppage': 62, 'pagenum': '076', 'sfx': 'png', 'word': '&sect; 104. Nouns from <span class="san">aYc</span>'},
        {'dir': 'files1/', 'disppage': 63, 'pagenum': '077', 'sfx': 'png', 'word': '<span class="san">prAYc</span>, <span class="san">pratyaYc</span>. <span class="san">tiryaYc</span>'},
        {'dir': 'files1/', 'disppage': 64, 'pagenum': '078', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 65, 'pagenum': '079', 'sfx': 'png', 'word': '<span class="section">Irregular bases</span>'},
        {'dir': 'files1/', 'disppage': 65, 'pagenum': '079', 'sfx': 'png', 'word': '&sect; 105. <span class="san">kruYc</span>'},
        {'dir': 'files1/', 'disppage': 66, 'pagenum': '080', 'sfx': 'png', 'word': '&sect; 105. <span class="san">Urj</span>'},
        {'dir': 'files1/', 'disppage': 66, 'pagenum': '080', 'sfx': 'png', 'word': '&sect; 106. Nouns in <span class="san">m</span>. <span class="san">praSAm</span>'},
        {'dir': 'files1/', 'disppage': 66, 'pagenum': '080', 'sfx': 'png', 'word': '&sect; 108. Nouns in <span class="san">s</span>. <span class="san">candramas</span>'},
        {'dir': 'files1/', 'disppage': 67, 'pagenum': '081', 'sfx': 'png', 'word': '<span class="san">manas</span>, <span class="san">udarcis</span>, <span class="san">suvas</span>'},
        {'dir': 'files1/', 'disppage': 68, 'pagenum': '082', 'sfx': 'png', 'word': '&sect; 110. <span class="san">BAs</span>. &sect; 112. Irregular bases'},
        {'dir': 'files1/', 'disppage': 69, 'pagenum': '083', 'sfx': 'png', 'word': '&sect; 113. <span class="san">puMs</span>. &sect; 113. <span class="san">pipaWiz</span>.'},
        {'dir': 'files1/', 'disppage': 70, 'pagenum': '084', 'sfx': 'png', 'word': '&sect; 115. Nouns in <span class="san">at</span>, <span class="san">mat</span>, and <span class="san">vat</span>. <span class="san">DImat</span>'},
        {'dir': 'files1/', 'disppage': 71, 'pagenum': '085', 'sfx': 'png', 'word': '<span class="san">mahatat</span>'},
        {'dir': 'files1/', 'disppage': 71, 'pagenum': '085', 'sfx': 'png', 'word': '&sect; 116. Participles ending in <span class="san">at</span>.'},
        {'dir': 'files1/', 'disppage': 72, 'pagenum': '086', 'sfx': 'png', 'word': '<span class="san">Bavat</span>, <span class="san">dadat</span>'},
        {'dir': 'files1/', 'disppage': 73, 'pagenum': '087', 'sfx': 'png', 'word': '&sect; 117. Nouns in <span class="san">an</span> and <span class="san">in</span>'},
        {'dir': 'files1/', 'disppage': 73, 'pagenum': '087', 'sfx': 'png', 'word': '<span class="san">brahman</span>, <span class="san">rAjan</span>'},
        {'dir': 'files1/', 'disppage': 74, 'pagenum': '088', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 75, 'pagenum': '089', 'sfx': 'png', 'word': '<span class="san">nAman</span>'},
        {'dir': 'files1/', 'disppage': 75, 'pagenum': '089', 'sfx': 'png', 'word': 'Irregular: &sect; 118. <span class="san">puzan</span>, <span class="san">vftrahan</span>'},
        {'dir': 'files1/', 'disppage': 76, 'pagenum': '090', 'sfx': 'png', 'word': '&sect; 119. <span class="san">Svan</span>'},
        {'dir': 'files1/', 'disppage': 77, 'pagenum': '091', 'sfx': 'png', 'word': '<span class="san">maGavan</span>, <span class="san">yuvan</span>'},
        {'dir': 'files1/', 'disppage': 77, 'pagenum': '091', 'sfx': 'png', 'word': '&sect; 120. <span class="san">ahan</span>'},
        {'dir': 'files1/', 'disppage': 78, 'pagenum': '092', 'sfx': 'png', 'word': '&sect; 121. <span class="san">arvan</span>'},
        {'dir': 'files1/', 'disppage': 78, 'pagenum': '092', 'sfx': 'png', 'word': '&sect; 122. Words in <span class="san">in</span>'},
        {'dir': 'files1/', 'disppage': 79, 'pagenum': '093', 'sfx': 'png', 'word': '<span class="san">karin</span>, <span class="san">daRqin</span>'},
        {'dir': 'files1/', 'disppage': 79, 'pagenum': '093', 'sfx': 'png', 'word': '&sect; 123. Irregular bases. <span class="san">paTin</span>'},
        {'dir': 'files1/', 'disppage': 80, 'pagenum': '094', 'sfx': 'png', 'word': '&sect; 124. Bases in <span class="san">vas</span>. <span class="san">vidvas</span>'},
        {'dir': 'files1/', 'disppage': 81, 'pagenum': '095', 'sfx': 'png', 'word': '&sect; 125. Bases in <span class="san">yas</span>, <span class="san">Iyas</span>. <span class="san">Sreyas</span>'},
        {'dir': 'files1/', 'disppage': 82, 'pagenum': '096', 'sfx': 'png', 'word': '<span class="section">Words of irregular declension</span>'},
        {'dir': 'files1/', 'disppage': 82, 'pagenum': '096', 'sfx': 'png', 'word': '&sect; 126-8. <span class="san">asTi</span>, <span class="san">ap</span>, <span class="san">jarA</span>'},
        {'dir': 'files1/', 'disppage': 83, 'pagenum': '097', 'sfx': 'png', 'word': '&sect; 129. <span class="san">dos</span>'},
        {'dir': 'files1/', 'disppage': 84, 'pagenum': '098', 'sfx': 'png', 'word': '<span class="san">niSA</span>, <span class="san">sAnu</span>, <span class="san">pAda</span>'},
        {'dir': 'files1/', 'disppage': 85, 'pagenum': '099', 'sfx': 'png', 'word': '<span class="san">danta</span>, <span class="san">nAsikA</span>, <span class="san">mAsa</span>, <span class="san">hfdaya</span>, <span class="san">asfj</span>'},
        {'dir': 'files1/', 'disppage': 86, 'pagenum': '100', 'sfx': 'png', 'word': '<span class="san">yUza</span>, <span class="san">yakft</span>, <span class="san">Sakft</span>, <span class="san">udaka</span>, <span class="san">Asya</span>'},
        {'dir': 'files1/', 'disppage': 87, 'pagenum': '101', 'sfx': 'png', 'word': '<span class="san">pftana</span>.'},
        {'dir': 'files1/', 'disppage': 87, 'pagenum': '101', 'sfx': 'png', 'word': '&sect; 130. Suffixes <span class="san">tas</span>, <span class="san">tra</span>'},
        {'dir': 'files1/', 'disppage': 87, 'pagenum': '101', 'sfx': 'png', 'word': '&sect; 131. Indeclineable nouns'}],
 '04': [{'dir': 'files1/', 'disppage': 87, 'pagenum': '101', 'sfx': 'png', 'word': '&sect; 132. pronouns'},
        {'dir': 'files1/', 'disppage': 88, 'pagenum': '102', 'sfx': 'png', 'word': '<span class="section">Personal Pronouns</span>'},
        {'dir': 'files1/', 'disppage': 88, 'pagenum': '102', 'sfx': 'png', 'word': '&sect; 133. <span class="san">asmad</span>, <span class="san">yuzmad</span>'},
        {'dir': 'files1/', 'disppage': 89, 'pagenum': '103', 'sfx': 'png', 'word': '&sect; 134. short forms of <span class="san">asmad</span>, <span class="san">yuzmad</span>'},
        {'dir': 'files1/', 'disppage': 90, 'pagenum': '104', 'sfx': 'png', 'word': '<span class="section">Demonstrative Pronouns</span>'},
        {'dir': 'files1/', 'disppage': 90, 'pagenum': '104', 'sfx': 'png', 'word': '&sect; 135. <span class="san">tad</span>'},
        {'dir': 'files1/', 'disppage': 91, 'pagenum': '105', 'sfx': 'png', 'word': '<span class="san">etad</span>'},
        {'dir': 'files1/', 'disppage': 92, 'pagenum': '106', 'sfx': 'png', 'word': '<span class="san">idam</span>, <span class="san">adas</span>'},
        {'dir': 'files1/', 'disppage': 93, 'pagenum': '107', 'sfx': 'png', 'word': '<span class="section">Relative Pronouns</span>'},
        {'dir': 'files1/', 'disppage': 94, 'pagenum': '108', 'sfx': 'png', 'word': '&sect; 138. <span class="san">yad</span>'},
        {'dir': 'files1/', 'disppage': 94, 'pagenum': '108', 'sfx': 'png', 'word': '<span class="section">Interrogative Pronouns</span>'},
        {'dir': 'files1/', 'disppage': 94, 'pagenum': '108', 'sfx': 'png', 'word': '&sect; 139. <span class="san">kim</span>'},
        {'dir': 'files1/', 'disppage': 95, 'pagenum': '109', 'sfx': 'png', 'word': '<span class="section">Reflexive Pronouns</span>'},
        {'dir': 'files1/', 'disppage': 95, 'pagenum': '109', 'sfx': 'png', 'word': '<span class="section">Indefinite Pronouns</span>'},
        {'dir': 'files1/', 'disppage': 95, 'pagenum': '109', 'sfx': 'png', 'word': '<span class="section">Correlative Pronouns</span>'},
        {'dir': 'files1/', 'disppage': 96, 'pagenum': '110', 'sfx': 'png', 'word': '<span class="section">Reciprocal Pronouns</span>'},
        {'dir': 'files1/', 'disppage': 96, 'pagenum': '110', 'sfx': 'png', 'word': '<span class="section">Possessive Pronouns</span>'},
        {'dir': 'files1/', 'disppage': 96, 'pagenum': '110', 'sfx': 'png', 'word': '&sect; 146. <span class="san">asmat</span>, <span class="san">yuzmat</span>'},
        {'dir': 'files1/', 'disppage': 97, 'pagenum': '111', 'sfx': 'png', 'word': '<span class="section">Pronominal Adjectives</span>'},
        {'dir': 'files1/', 'disppage': 97, 'pagenum': '111', 'sfx': 'png', 'word': '&sect; 147. <span class="san">katara</span>'},
        {'dir': 'files1/', 'disppage': 98, 'pagenum': '112', 'sfx': 'png', 'word': '<span class="san">sarva</span>'},
        {'dir': 'files1/', 'disppage': 99, 'pagenum': '113', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 100, 'pagenum': '114', 'sfx': 'png', 'word': '<span class="section">Pronominal Adverbs</span>'},
        {'dir': 'files1/', 'disppage': 101, 'pagenum': '115', 'sfx': 'png', 'word': ''}],
 '05': [{'dir': 'files1/', 'disppage': 102, 'pagenum': '116', 'sfx': 'png', 'word': '&sect; 159. Cardinals/Ordinals 1-16'}, {'dir': 'files1/', 'disppage': 103, 'pagenum': '117', 'sfx': 'png', 'word': 'Cardinals/Ordinals 17-41'}, {'dir': 'files1/', 'disppage': 104, 'pagenum': '118', 'sfx': 'png', 'word': 'Cardinals/Ordinals 42-67'}, {'dir': 'files1/', 'disppage': 105, 'pagenum': '119', 'sfx': 'png', 'word': 'Cardinals/Ordinals 68-93'}, {'dir': 'files1/', 'disppage': 106, 'pagenum': '120', 'sfx': 'png', 'word': 'Cardinals/Ordinals 94-100, etc.'}, {'dir': 'files1/', 'disppage': 107, 'pagenum': '121', 'sfx': 'png', 'word': ''}, {'dir': 'files1/', 'disppage': 108, 'pagenum': '122', 'sfx': 'png', 'word': '&sect; 165. <span class="san">tri</span>, <span class="san">catur</span>, <span class="san">paYcan</span>'}, {'dir': 'files1/', 'disppage': 109, 'pagenum': '123', 'sfx': 'png', 'word': '<span class="section">Numeral Adverbs</span>'}],
 '06': [{'dir': 'files1/', 'disppage': 110, 'pagenum': '124', 'sfx': 'png', 'word': '&sect; 171. <span class="san">tara</span>, <span class="san">tama</span>'}, {'dir': 'files1/', 'disppage': 111, 'pagenum': '125', 'sfx': 'png', 'word': '&sect; 174. <span class="san">Iyas</span>, <span class="san">izwa</span>'}, {'dir': 'files1/', 'disppage': 112, 'pagenum': '126', 'sfx': 'png', 'word': '&sect; 177. Irregular comparatives and superlatives'}],
 '07': [{'dir': 'files1/', 'disppage': 113, 'pagenum': '127', 'sfx': 'png', 'word': 'VII. Compounds'},
        {'dir': 'files1/', 'disppage': 114, 'pagenum': '128', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 115, 'pagenum': '129', 'sfx': 'png', 'word': '1 Dwandwa compounds'},
        {'dir': 'files1/', 'disppage': 116, 'pagenum': '130', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 117, 'pagenum': '131', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 118, 'pagenum': '132', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 119, 'pagenum': '133', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 120, 'pagenum': '134', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 121, 'pagenum': '135', 'sfx': 'png', 'word': '2 Tatpurusha compounds'},
        {'dir': 'files1/', 'disppage': 122, 'pagenum': '136', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 123, 'pagenum': '137', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 124, 'pagenum': '138', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 125, 'pagenum': '139', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 126, 'pagenum': '140', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 127, 'pagenum': '141', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 128, 'pagenum': '142', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 129, 'pagenum': '143', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 130, 'pagenum': '144', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 131, 'pagenum': '145', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 132, 'pagenum': '146', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 133, 'pagenum': '147', 'sfx': 'png', 'word': '3 Karmadharaya compounds'},
        {'dir': 'files1/', 'disppage': 134, 'pagenum': '148', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 135, 'pagenum': '149', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 136, 'pagenum': '150', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 137, 'pagenum': '151', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 138, 'pagenum': '152', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 139, 'pagenum': '153', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 140, 'pagenum': '154', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 141, 'pagenum': '155', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 142, 'pagenum': '156', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 143, 'pagenum': '157', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 144, 'pagenum': '158', 'sfx': 'png', 'word': '4 Upapada compounds'},
        {'dir': 'files1/', 'disppage': 145, 'pagenum': '159', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 146, 'pagenum': '160', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 147, 'pagenum': '161', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 148, 'pagenum': '162', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 149, 'pagenum': '163', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 150, 'pagenum': '164', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 151, 'pagenum': '165', 'sfx': 'png', 'word': '5 Bahuvrihi compounds'},
        {'dir': 'files1/', 'disppage': 152, 'pagenum': '166', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 153, 'pagenum': '167', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 154, 'pagenum': '168', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 155, 'pagenum': '169', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 156, 'pagenum': '170', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 157, 'pagenum': '171', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 158, 'pagenum': '172', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 159, 'pagenum': '173', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 160, 'pagenum': '174', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 161, 'pagenum': '175', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 162, 'pagenum': '176', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 163, 'pagenum': '177', 'sfx': 'png', 'word': '6 Avyayibhava compounds'},
        {'dir': 'files1/', 'disppage': 164, 'pagenum': '178', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 165, 'pagenum': '179', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 166, 'pagenum': '180', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 167, 'pagenum': '181', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 168, 'pagenum': '182', 'sfx': 'png', 'word': '7 General rules for compounds'},
        {'dir': 'files1/', 'disppage': 169, 'pagenum': '183', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 170, 'pagenum': '184', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 171, 'pagenum': '185', 'sfx': 'png', 'word': '8 Other changes for compounds'},
        {'dir': 'files1/', 'disppage': 172, 'pagenum': '186', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 173, 'pagenum': '187', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 174, 'pagenum': '188', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 175, 'pagenum': '189', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 176, 'pagenum': '190', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 177, 'pagenum': '191', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 178, 'pagenum': '192', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 179, 'pagenum': '193', 'sfx': 'png', 'word': ''}],
 '08': [{'dir': 'files1/', 'disppage': 180, 'pagenum': '194', 'sfx': 'png', 'word': 'VIII. Formation of Feminine Bases'},
        {'dir': 'files1/', 'disppage': 181, 'pagenum': '195', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 182, 'pagenum': '196', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 183, 'pagenum': '197', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 184, 'pagenum': '198', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 185, 'pagenum': '199', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 186, 'pagenum': '200', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 187, 'pagenum': '201', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 188, 'pagenum': '202', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 189, 'pagenum': '203', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 190, 'pagenum': '204', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 191, 'pagenum': '205', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 192, 'pagenum': '206', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 193, 'pagenum': '207', 'sfx': 'png', 'word': ''}],
 '09': [{'dir': 'files1/', 'disppage': 194, 'pagenum': '208', 'sfx': 'png', 'word': '<span class="san">tadDita</span> affixes'},
        {'dir': 'files1/', 'disppage': 195, 'pagenum': '209', 'sfx': 'png', 'word': '<span class="section">miscellaneous affixes</span>'},
        {'dir': 'files1/', 'disppage': 196, 'pagenum': '210', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 197, 'pagenum': '211', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 198, 'pagenum': '212', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 199, 'pagenum': '213', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 200, 'pagenum': '214', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 201, 'pagenum': '215', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 202, 'pagenum': '216', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 203, 'pagenum': '217', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 204, 'pagenum': '218', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 205, 'pagenum': '219', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 206, 'pagenum': '220', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 207, 'pagenum': '221', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 208, 'pagenum': '222', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 209, 'pagenum': '223', 'sfx': 'png', 'word': '<span class="section">Affixes showing possession</span>'},
        {'dir': 'files1/', 'disppage': 210, 'pagenum': '224', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 211, 'pagenum': '225', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 212, 'pagenum': '226', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 213, 'pagenum': '227', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 214, 'pagenum': '228', 'sfx': 'png', 'word': '<span class="section">Affixes forming adverbs</span>'},
        {'dir': 'files1/', 'disppage': 215, 'pagenum': '229', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 216, 'pagenum': '230', 'sfx': 'png', 'word': '<span class="section">Irregular adverbs of time</span>'}],
 '10': [{'dir': 'files1/', 'disppage': 216, 'pagenum': '230', 'sfx': 'png', 'word': 'X. Gender'}, {'dir': 'files1/', 'disppage': 217, 'pagenum': '231', 'sfx': 'png', 'word': '<span class="section">Masculine words</span>'}, {'dir': 'files1/', 'disppage': 218, 'pagenum': '232', 'sfx': 'png', 'word': ''}, {'dir': 'files1/', 'disppage': 219, 'pagenum': '233', 'sfx': 'png', 'word': '<span class="section">Feminine words</span>'}, {'dir': 'files1/', 'disppage': 220, 'pagenum': '234', 'sfx': 'png', 'word': '<span class="section">Neuter words</span>'}, {'dir': 'files1/', 'disppage': 221, 'pagenum': '235', 'sfx': 'png', 'word': '<span class="section">Words masculine and feminine</span>'}, {'dir': 'files1/', 'disppage': 222, 'pagenum': '236', 'sfx': 'png', 'word': '<span class="section">Words masculine and neuter</span>'}, {'dir': 'files1/', 'disppage': 223, 'pagenum': '237', 'sfx': 'png', 'word': '<span class="section">Words feminine and neuter</span>'}],
 '11': [{'dir': 'files1/', 'disppage': 223, 'pagenum': '237', 'sfx': 'png', 'word': 'XI. Avyayas or Indeclinables'},
        {'dir': 'files1/', 'disppage': 224, 'pagenum': '238', 'sfx': 'png', 'word': '<span class="section">Prepositions</span>'},
        {'dir': 'files1/', 'disppage': 225, 'pagenum': '239', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 226, 'pagenum': '240', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 227, 'pagenum': '241', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 228, 'pagenum': '242', 'sfx': 'png', 'word': '<span class="section">Adverbs</span>'},
        {'dir': 'files1/', 'disppage': 229, 'pagenum': '243', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 230, 'pagenum': '244', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 231, 'pagenum': '245', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 232, 'pagenum': '246', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 233, 'pagenum': '247', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 234, 'pagenum': '248', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 235, 'pagenum': '249', 'sfx': 'png', 'word': '<span class="section">Particles</span>'},
        {'dir': 'files1/', 'disppage': 236, 'pagenum': '250', 'sfx': 'png', 'word': '<span class="section">Conjunctions</span>'},
        {'dir': 'files1/', 'disppage': 237, 'pagenum': '251', 'sfx': 'png', 'word': '<span class="section">Interjections</span>'}],
 '12': [{'dir': 'files1/', 'disppage': 238, 'pagenum': '252', 'sfx': 'png', 'word': 'XII. Conjugation of Verbs'},
        {'dir': 'files1/', 'disppage': 239, 'pagenum': '253', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 240, 'pagenum': '254', 'sfx': 'png', 'word': '<span class="section">Active voice</span>'},
        {'dir': 'files1/', 'disppage': 241, 'pagenum': '255', 'sfx': 'png', 'word': '<span class="section">Classes 1,4,6,10</span>'},
        {'dir': 'files1/', 'disppage': 242, 'pagenum': '256', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 243, 'pagenum': '257', 'sfx': 'png', 'word': 'nI'},
        {'dir': 'files1/', 'disppage': 244, 'pagenum': '258', 'sfx': 'png', 'word': 'buD, Izk, nI, BU, laB'},
        {'dir': 'files1/', 'disppage': 245, 'pagenum': '259', 'sfx': 'png', 'word': 'smf, mud, tuz, yuD'},
        {'dir': 'files1/', 'disppage': 246, 'pagenum': '260', 'sfx': 'png', 'word': 'kzip'},
        {'dir': 'files1/', 'disppage': 247, 'pagenum': '261', 'sfx': 'png', 'word': 'cur'},
        {'dir': 'files1/', 'disppage': 248, 'pagenum': '262', 'sfx': 'png', 'word': '<span class="section">Classes 1,4,6,10 (Irregular)</span> '},
        {'dir': 'files1/', 'disppage': 248, 'pagenum': '262', 'sfx': 'png', 'word': '<span class="section">class 1.</span> gup, DUp, vicC, paR'},
        {'dir': 'files1/', 'disppage': 249, 'pagenum': '263', 'sfx': 'png', 'word': 'guh, kAm, zWiv, cam, BrAS, BlAS, '},
        {'dir': 'files1/', 'disppage': 249, 'pagenum': '263', 'sfx': 'png', 'word': 'Bram, kram, laz, Dinv, kfRv, akz, '},
        {'dir': 'files1/', 'disppage': 249, 'pagenum': '263', 'sfx': 'png', 'word': 'takz, ft, gam, yam, pA, GrA, DmA, '},
        {'dir': 'files1/', 'disppage': 249, 'pagenum': '263', 'sfx': 'png', 'word': 'sTA, mnA, dA, dfS, f,'},
        {'dir': 'files1/', 'disppage': 250, 'pagenum': '264', 'sfx': 'png', 'word': 'sf, Sad, sad, daMS, svaYj, raYj'},
        {'dir': 'files1/', 'disppage': 250, 'pagenum': '264', 'sfx': 'png', 'word': 'mfj, jaB, kxp (?), lasj, sasj'},
        {'dir': 'files1/', 'disppage': 250, 'pagenum': '264', 'sfx': 'png', 'word': '<span class="section">class 4.</span> kram, jan, Sam, tam, '},
        {'dir': 'files1/', 'disppage': 251, 'pagenum': '265', 'sfx': 'png', 'word': 'dam, Sram, kzam, klam, mad, yas, '},
        {'dir': 'files1/', 'disppage': 251, 'pagenum': '265', 'sfx': 'png', 'word': 'So, Co, so, do,BraMS, BraMs, raMj, '},
        {'dir': 'files1/', 'disppage': 251, 'pagenum': '265', 'sfx': 'png', 'word': 'mid, vyaD'},
        {'dir': 'files1/', 'disppage': 251, 'pagenum': '265', 'sfx': 'png', 'word': '<span class="section">class 6.</span> iz, kft, ku, Hid, gF, truw, '},
        {'dir': 'files1/', 'disppage': 251, 'pagenum': '265', 'sfx': 'png', 'word': 'pracC, Brasj, masj, vraSc, vyac, vicC, '},
        {'dir': 'files1/', 'disppage': 251, 'pagenum': '265', 'sfx': 'png', 'word': 'sasj, muc, lip, '},
        {'dir': 'files1/', 'disppage': 252, 'pagenum': '266', 'sfx': 'png', 'word': 'lup, vid, sic, piS'},
        {'dir': 'files1/', 'disppage': 252, 'pagenum': '266', 'sfx': 'png', 'word': '<span class="section">class 10.</span> DU, arT, lajj, prI, gaR, vaRw'},
        {'dir': 'files1/', 'disppage': 252, 'pagenum': '266', 'sfx': 'png', 'word': '(roots with unchanged vowel) '},
        {'dir': 'files1/', 'disppage': 252, 'pagenum': '266', 'sfx': 'png', 'word': '(roots with Atmanepada only)'},
        {'dir': 'files1/', 'disppage': 254, 'pagenum': '268', 'sfx': 'png', 'word': '(roots in class 1 and 10)'},
        {'dir': 'files1/', 'disppage': 254, 'pagenum': '268', 'sfx': 'png', 'word': '<span class="section">Classes 2,3,5,7,8,9</span>'},
        {'dir': 'files1/', 'disppage': 255, 'pagenum': '269', 'sfx': 'png', 'word': 'Endings and strengths'},
        {'dir': 'files1/', 'disppage': 256, 'pagenum': '270', 'sfx': 'png', 'word': '<span class="section">Classes 5, 8, 9.</span>'},
        {'dir': 'files1/', 'disppage': 256, 'pagenum': '270', 'sfx': 'png', 'word': '<span class="section">Class 5.</span> su'},
        {'dir': 'files1/', 'disppage': 257, 'pagenum': '271', 'sfx': 'png', 'word': 'sAD, aS'},
        {'dir': 'files1/', 'disppage': 258, 'pagenum': '272', 'sfx': 'png', 'word': '<span class="section">Class 8.</span> tan'},
        {'dir': 'files1/', 'disppage': 259, 'pagenum': '273', 'sfx': 'png', 'word': 'Irregular base: kf.  '},
        {'dir': 'files1/', 'disppage': 259, 'pagenum': '273', 'sfx': 'png', 'word': '<span class="section">Class 9.</span> krI,'},
        {'dir': 'files1/', 'disppage': 260, 'pagenum': '274', 'sfx': 'png', 'word': 'stamB. '},
        {'dir': 'files1/', 'disppage': 260, 'pagenum': '274', 'sfx': 'png', 'word': '<span class="section">Class 9 Irregulars.</span> kzuB, jYA, jyA'},
        {'dir': 'files1/', 'disppage': 261, 'pagenum': '275', 'sfx': 'png', 'word': 'grah. '},
        {'dir': 'files1/', 'disppage': 261, 'pagenum': '275', 'sfx': 'png', 'word': 'rI, lI, vlI, plI, DU, pU, lU, FM (?),'},
        {'dir': 'files1/', 'disppage': 261, 'pagenum': '275', 'sfx': 'png', 'word': 'kF, gF, jF, nF, pF, BF, mF, vF, SF, stF'},
        {'dir': 'files1/', 'disppage': 261, 'pagenum': '275', 'sfx': 'png', 'word': 'kzI, mrI, vrI.  '},
        {'dir': 'files1/', 'disppage': 261, 'pagenum': '275', 'sfx': 'png', 'word': 'sku, stamB, stumB, skamB, skumB (classes 5,9)'},
        {'dir': 'files1/', 'disppage': 261, 'pagenum': '275', 'sfx': 'png', 'word': '<span class="section">Classes 2,3 and 7.</span>'},
        {'dir': 'files1/', 'disppage': 262, 'pagenum': '276', 'sfx': 'png', 'word': '<span class="section">Class 2</span>'},
        {'dir': 'files1/', 'disppage': 263, 'pagenum': '277', 'sfx': 'png', 'word': 'yA, (KyA, dA, pA, prA, psA, drA, BA,'},
        {'dir': 'files1/', 'disppage': 263, 'pagenum': '277', 'sfx': 'png', 'word': 'mA, rA, lA, vA, SrA, snA)  vI'},
        {'dir': 'files1/', 'disppage': 264, 'pagenum': '278', 'sfx': 'png', 'word': 'nu (ku, kzu, kzRu, dyu, yu, su, snu)'},
        {'dir': 'files1/', 'disppage': 264, 'pagenum': '278', 'sfx': 'png', 'word': 'jAgf'},
        {'dir': 'files1/', 'disppage': 265, 'pagenum': '279', 'sfx': 'png', 'word': 'Ir, cakz, kaS'},
        {'dir': 'files1/', 'disppage': 266, 'pagenum': '280', 'sfx': 'png', 'word': 'duh (dih)'},
        {'dir': 'files1/', 'disppage': 267, 'pagenum': '281', 'sfx': 'png', 'word': 'lih, niYj'},
        {'dir': 'files1/', 'disppage': 268, 'pagenum': '282', 'sfx': 'png', 'word': '<span class="section">Class 2 Irregular</span>'},
        {'dir': 'files1/', 'disppage': 268, 'pagenum': '282', 'sfx': 'png', 'word': 'ad. an, jakz, rud, Svas, svap. an.'},
        {'dir': 'files1/', 'disppage': 269, 'pagenum': '283', 'sfx': 'png', 'word': 'as'},
        {'dir': 'files1/', 'disppage': 270, 'pagenum': '284', 'sfx': 'png', 'word': 'As (vas).  i'},
        {'dir': 'files1/', 'disppage': 271, 'pagenum': '285', 'sfx': 'png', 'word': 'aDI. Iq, IS. UrRu'},
        {'dir': 'files1/', 'disppage': 272, 'pagenum': '286', 'sfx': 'png', 'word': 'UrRu. cakAs (jakz, jAgf, daridrA, SAs)'},
        {'dir': 'files1/', 'disppage': 273, 'pagenum': '287', 'sfx': 'png', 'word': 'jakz. daridrA'},
        {'dir': 'files1/', 'disppage': 274, 'pagenum': '288', 'sfx': 'png', 'word': 'dviz. brU'},
        {'dir': 'files1/', 'disppage': 275, 'pagenum': '289', 'sfx': 'png', 'word': 'mfj '},
        {'dir': 'files1/', 'disppage': 276, 'pagenum': '290', 'sfx': 'png', 'word': 'vac. vaS'},
        {'dir': 'files1/', 'disppage': 277, 'pagenum': '291', 'sfx': 'png', 'word': 'vid. SAs'},
        {'dir': 'files1/', 'disppage': 278, 'pagenum': '292', 'sfx': 'png', 'word': 'SI, sU, (stu, tu, ru)'},
        {'dir': 'files1/', 'disppage': 279, 'pagenum': '293', 'sfx': 'png', 'word': 'stu'},
        {'dir': 'files1/', 'disppage': 280, 'pagenum': '294', 'sfx': 'png', 'word': 'han'},
        {'dir': 'files1/', 'disppage': 281, 'pagenum': '295', 'sfx': 'png', 'word': 'hnu'},
        {'dir': 'files1/', 'disppage': 281, 'pagenum': '295', 'sfx': 'png', 'word': '<span class="section">Class 3</span>'},
        {'dir': 'files1/', 'disppage': 282, 'pagenum': '296', 'sfx': 'png', 'word': 'ki'},
        {'dir': 'files1/', 'disppage': 283, 'pagenum': '297', 'sfx': 'png', 'word': 'hu, hrI,'},
        {'dir': 'files1/', 'disppage': 283, 'pagenum': '297', 'sfx': 'png', 'word': '<span class="section">Class 3 Irregular bases</span>'},
        {'dir': 'files1/', 'disppage': 283, 'pagenum': '297', 'sfx': 'png', 'word': 'mA, hA, Bf, pf, pF.  nij, vij, viz'},
        {'dir': 'files1/', 'disppage': 284, 'pagenum': '298', 'sfx': 'png', 'word': 'dA, DA. BI, mA, hA.'},
        {'dir': 'files1/', 'disppage': 284, 'pagenum': '298', 'sfx': 'png', 'word': 'f, DA (dA)'},
        {'dir': 'files1/', 'disppage': 285, 'pagenum': '299', 'sfx': 'png', 'word': 'nij (vij)'},
        {'dir': 'files1/', 'disppage': 286, 'pagenum': '300', 'sfx': 'png', 'word': 'pf, pF'},
        {'dir': 'files1/', 'disppage': 287, 'pagenum': '301', 'sfx': 'png', 'word': 'BI, Bf'},
        {'dir': 'files1/', 'disppage': 288, 'pagenum': '302', 'sfx': 'png', 'word': 'mA, viz'},
        {'dir': 'files1/', 'disppage': 289, 'pagenum': '303', 'sfx': 'png', 'word': 'hA'},
        {'dir': 'files1/', 'disppage': 290, 'pagenum': '304', 'sfx': 'png', 'word': '<span class="section">class 7</span>'},
        {'dir': 'files1/', 'disppage': 290, 'pagenum': '304', 'sfx': 'png', 'word': 'aYj, inD'},
        {'dir': 'files1/', 'disppage': 291, 'pagenum': '305', 'sfx': 'png', 'word': 'kzud (Bid, und, Kid, Cid, Cfd,'},
        {'dir': 'files1/', 'disppage': 291, 'pagenum': '305', 'sfx': 'png', 'word': 'kft, tfh, svid)  tfh'},
        {'dir': 'files1/', 'disppage': 292, 'pagenum': '306', 'sfx': 'png', 'word': 'piz, yuj'},
        {'dir': 'files1/', 'disppage': 293, 'pagenum': '307', 'sfx': 'png', 'word': '(BaYj, Buj, vij, vfj).  '},
        {'dir': 'files1/', 'disppage': 293, 'pagenum': '307', 'sfx': 'png', 'word': 'ric (vic, taYc, pfc)'},
        {'dir': 'files1/', 'disppage': 294, 'pagenum': '308', 'sfx': 'png', 'word': 'ruD'},
        {'dir': 'files1/', 'disppage': 295, 'pagenum': '309', 'sfx': 'png', 'word': 'hiMs'},
        {'dir': 'files1/', 'disppage': 295, 'pagenum': '309', 'sfx': 'png', 'word': '<span class="section">General tenses and moods</span>'},
        {'dir': 'files1/', 'disppage': 296, 'pagenum': '310', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 297, 'pagenum': '311', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 298, 'pagenum': '312', 'sfx': 'png', 'word': 'a. <span class="section">First future</span>'},
        {'dir': 'files1/', 'disppage': 299, 'pagenum': '313', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 300, 'pagenum': '314', 'sfx': 'png', 'word': 'b. <span class="section">Second future and conditional</span>'},
        {'dir': 'files1/', 'disppage': 301, 'pagenum': '315', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 302, 'pagenum': '316', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 303, 'pagenum': '317', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 304, 'pagenum': '318', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 305, 'pagenum': '319', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 306, 'pagenum': '320', 'sfx': 'png', 'word': 'c. <span class="section">Perfect</span>'},
        {'dir': 'files1/', 'disppage': 307, 'pagenum': '321', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 308, 'pagenum': '322', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 309, 'pagenum': '323', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 310, 'pagenum': '324', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 311, 'pagenum': '325', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 312, 'pagenum': '326', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 313, 'pagenum': '327', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 314, 'pagenum': '328', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 315, 'pagenum': '329', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 316, 'pagenum': '330', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 317, 'pagenum': '331', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 318, 'pagenum': '332', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 319, 'pagenum': '333', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 320, 'pagenum': '334', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 321, 'pagenum': '335', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 322, 'pagenum': '336', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 323, 'pagenum': '337', 'sfx': 'png', 'word': 'c1. <span class="section">Irregular bases</span>'},
        {'dir': 'files1/', 'disppage': 324, 'pagenum': '338', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 325, 'pagenum': '339', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 326, 'pagenum': '340', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 327, 'pagenum': '341', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 328, 'pagenum': '342', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 329, 'pagenum': '343', 'sfx': 'png', 'word': 'c2. <span class="section">Periphrastic perfect</span>'},
        {'dir': 'files1/', 'disppage': 330, 'pagenum': '344', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 331, 'pagenum': '345', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 332, 'pagenum': '346', 'sfx': 'png', 'word': 'd. <span class="section">Aorist - 1st variety</span>'},
        {'dir': 'files1/', 'disppage': 333, 'pagenum': '347', 'sfx': 'png', 'word': '<span class="section">Aorist - 2nd variety</span>'},
        {'dir': 'files1/', 'disppage': 334, 'pagenum': '348', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 335, 'pagenum': '349', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 336, 'pagenum': '350', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 337, 'pagenum': '351', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 338, 'pagenum': '352', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 339, 'pagenum': '353', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 340, 'pagenum': '354', 'sfx': 'png', 'word': '<span class="section">Aorist - 3rd variety</span>'},
        {'dir': 'files1/', 'disppage': 341, 'pagenum': '355', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 342, 'pagenum': '356', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 343, 'pagenum': '357', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 344, 'pagenum': '358', 'sfx': 'png', 'word': '<span class="section">Aorist - 6th variety</span>'},
        {'dir': 'files1/', 'disppage': 345, 'pagenum': '359', 'sfx': 'png', 'word': '<span class="section">Aorist - 7th variety</span>'},
        {'dir': 'files1/', 'disppage': 346, 'pagenum': '360', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 347, 'pagenum': '361', 'sfx': 'png', 'word': '<span class="section">Aorist - 4th variety</span>'},
        {'dir': 'files1/', 'disppage': 348, 'pagenum': '362', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 349, 'pagenum': '363', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 350, 'pagenum': '364', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 351, 'pagenum': '365', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 352, 'pagenum': '366', 'sfx': 'png', 'word': '<span class="section">Aorist - 5th variety</span>'},
        {'dir': 'files1/', 'disppage': 353, 'pagenum': '367', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 354, 'pagenum': '368', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 355, 'pagenum': '369', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 356, 'pagenum': '370', 'sfx': 'png', 'word': 'e. <span class="section">Benedictive</span>'},
        {'dir': 'files1/', 'disppage': 357, 'pagenum': '371', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 358, 'pagenum': '372', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 359, 'pagenum': '373', 'sfx': 'png', 'word': '<span class="section">Passive voice</span>'},
        {'dir': 'files1/', 'disppage': 360, 'pagenum': '374', 'sfx': 'png', 'word': '<span class="section">Passive: conjugational tenses</span>'},
        {'dir': 'files1/', 'disppage': 361, 'pagenum': '375', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 362, 'pagenum': '376', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 363, 'pagenum': '377', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 364, 'pagenum': '378', 'sfx': 'png', 'word': '<span class="section">Passive: general tenses/moods</span>'},
        {'dir': 'files1/', 'disppage': 365, 'pagenum': '379', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 366, 'pagenum': '380', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 367, 'pagenum': '381', 'sfx': 'png', 'word': '<span class="section">Derivative Verbs</span>'},
        {'dir': 'files1/', 'disppage': 368, 'pagenum': '382', 'sfx': 'png', 'word': 'a. <span class="section">Causals</span>'},
        {'dir': 'files1/', 'disppage': 369, 'pagenum': '383', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 370, 'pagenum': '384', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 371, 'pagenum': '385', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 372, 'pagenum': '386', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 373, 'pagenum': '387', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 374, 'pagenum': '388', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 375, 'pagenum': '389', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 376, 'pagenum': '390', 'sfx': 'png', 'word': 'b. <span class="section">Desideratives</span>'},
        {'dir': 'files1/', 'disppage': 377, 'pagenum': '391', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 378, 'pagenum': '392', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 379, 'pagenum': '393', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 380, 'pagenum': '394', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 381, 'pagenum': '395', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 382, 'pagenum': '396', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 383, 'pagenum': '397', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 384, 'pagenum': '398', 'sfx': 'png', 'word': 'c. <span class="section">Frequentatives</span>'},
        {'dir': 'files1/', 'disppage': 385, 'pagenum': '399', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 386, 'pagenum': '400', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 387, 'pagenum': '401', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 388, 'pagenum': '402', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 389, 'pagenum': '403', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 390, 'pagenum': '404', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 391, 'pagenum': '405', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 392, 'pagenum': '406', 'sfx': 'png', 'word': 'd. <span class="section">Nominal Verbs</span>'},
        {'dir': 'files1/', 'disppage': 393, 'pagenum': '407', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 394, 'pagenum': '408', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 395, 'pagenum': '409', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 396, 'pagenum': '410', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 397, 'pagenum': '411', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 398, 'pagenum': '412', 'sfx': 'png', 'word': ''}],
 '13': [{'dir': 'files1/', 'disppage': 399, 'pagenum': '413', 'sfx': 'png', 'word': 'XIII. Parasmaipada / Atmanepada'},
        {'dir': 'files1/', 'disppage': 400, 'pagenum': '414', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 401, 'pagenum': '415', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 402, 'pagenum': '416', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 403, 'pagenum': '417', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 404, 'pagenum': '418', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 405, 'pagenum': '419', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 406, 'pagenum': '420', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 407, 'pagenum': '421', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 408, 'pagenum': '422', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 409, 'pagenum': '423', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 410, 'pagenum': '424', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 411, 'pagenum': '425', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 412, 'pagenum': '426', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 413, 'pagenum': '427', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 414, 'pagenum': '428', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 415, 'pagenum': '429', 'sfx': 'png', 'word': ''}],
 '14': [{'dir': 'files1/', 'disppage': 416, 'pagenum': '430', 'sfx': 'png', 'word': 'XIV. Verbal Derivatives'},
        {'dir': 'files1/', 'disppage': 417, 'pagenum': '431', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 418, 'pagenum': '432', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 419, 'pagenum': '433', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 420, 'pagenum': '434', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 421, 'pagenum': '435', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 422, 'pagenum': '436', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 423, 'pagenum': '437', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 424, 'pagenum': '438', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 425, 'pagenum': '439', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 426, 'pagenum': '440', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 427, 'pagenum': '441', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 428, 'pagenum': '442', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 429, 'pagenum': '443', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 430, 'pagenum': '444', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 431, 'pagenum': '445', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 432, 'pagenum': '446', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 433, 'pagenum': '447', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 434, 'pagenum': '448', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 435, 'pagenum': '449', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 436, 'pagenum': '450', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 437, 'pagenum': '451', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 438, 'pagenum': '452', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 439, 'pagenum': '453', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 440, 'pagenum': '454', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 441, 'pagenum': '455', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 442, 'pagenum': '456', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 443, 'pagenum': '457', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 444, 'pagenum': '458', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 445, 'pagenum': '459', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 446, 'pagenum': '460', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 447, 'pagenum': '461', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 448, 'pagenum': '462', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 449, 'pagenum': '463', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 450, 'pagenum': '464', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 451, 'pagenum': '465', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 452, 'pagenum': '466', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 453, 'pagenum': '467', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 454, 'pagenum': '468', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 455, 'pagenum': '469', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 456, 'pagenum': '470', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 457, 'pagenum': '471', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 458, 'pagenum': '472', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 459, 'pagenum': '473', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 460, 'pagenum': '474', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 461, 'pagenum': '475', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 462, 'pagenum': '476', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 463, 'pagenum': '477', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 464, 'pagenum': '478', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 465, 'pagenum': '479', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 466, 'pagenum': '480', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 467, 'pagenum': '481', 'sfx': 'png', 'word': ''}],
 '15': [{'dir': 'files1/', 'disppage': 468, 'pagenum': '482', 'sfx': 'png', 'word': 'XV. Syntax'},
        {'dir': 'files1/', 'disppage': 469, 'pagenum': '483', 'sfx': 'png', 'word': 'The article'},
        {'dir': 'files1/', 'disppage': 470, 'pagenum': '484', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 471, 'pagenum': '485', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 472, 'pagenum': '486', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 473, 'pagenum': '487', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 474, 'pagenum': '488', 'sfx': 'png', 'word': 'Concord'},
        {'dir': 'files1/', 'disppage': 475, 'pagenum': '489', 'sfx': 'png', 'word': 'Government'},
        {'dir': 'files1/', 'disppage': 476, 'pagenum': '490', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 477, 'pagenum': '491', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 478, 'pagenum': '492', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 479, 'pagenum': '493', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 480, 'pagenum': '494', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 481, 'pagenum': '495', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 482, 'pagenum': '496', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 483, 'pagenum': '497', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 484, 'pagenum': '498', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 485, 'pagenum': '499', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 486, 'pagenum': '500', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 487, 'pagenum': '501', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 488, 'pagenum': '502', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 489, 'pagenum': '503', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 490, 'pagenum': '504', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 491, 'pagenum': '505', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 492, 'pagenum': '506', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 493, 'pagenum': '507', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 494, 'pagenum': '508', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 495, 'pagenum': '509', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 496, 'pagenum': '510', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 497, 'pagenum': '511', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 498, 'pagenum': '512', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 499, 'pagenum': '513', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 500, 'pagenum': '514', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 501, 'pagenum': '515', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 502, 'pagenum': '516', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 503, 'pagenum': '517', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 504, 'pagenum': '518', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 505, 'pagenum': '519', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 506, 'pagenum': '520', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 507, 'pagenum': '521', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 508, 'pagenum': '522', 'sfx': 'png', 'word': 'Pronouns'},
        {'dir': 'files1/', 'disppage': 509, 'pagenum': '523', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 510, 'pagenum': '524', 'sfx': 'png', 'word': 'Comparative and superlative'},
        {'dir': 'files1/', 'disppage': 511, 'pagenum': '525', 'sfx': 'png', 'word': 'Participles'},
        {'dir': 'files1/', 'disppage': 512, 'pagenum': '526', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 513, 'pagenum': '527', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 514, 'pagenum': '528', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 515, 'pagenum': '529', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 516, 'pagenum': '530', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 517, 'pagenum': '531', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 518, 'pagenum': '532', 'sfx': 'png', 'word': 'Tenses and moods'},
        {'dir': 'files1/', 'disppage': 519, 'pagenum': '533', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 520, 'pagenum': '534', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 521, 'pagenum': '535', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 522, 'pagenum': '536', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 523, 'pagenum': '537', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 524, 'pagenum': '538', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 525, 'pagenum': '539', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 526, 'pagenum': '540', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 527, 'pagenum': '541', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 528, 'pagenum': '542', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 529, 'pagenum': '543', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 530, 'pagenum': '544', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 531, 'pagenum': '545', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 532, 'pagenum': '546', 'sfx': 'png', 'word': 'Indeclineables'},
        {'dir': 'files1/', 'disppage': 533, 'pagenum': '547', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 534, 'pagenum': '548', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 535, 'pagenum': '549', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 536, 'pagenum': '550', 'sfx': 'png', 'word': ''}],
 'DK': [{'dir': 'files1/', 'disppage': 1, 'pagenum': '551', 'sfx': 'png', 'word': 'Appendix II: Dhatukosha, aMS'},
        {'dir': 'files1/', 'disppage': 2, 'pagenum': '552', 'sfx': 'png', 'word': 'ag'},
        {'dir': 'files1/', 'disppage': 3, 'pagenum': '553', 'sfx': 'png', 'word': 'aYc'},
        {'dir': 'files1/', 'disppage': 4, 'pagenum': '554', 'sfx': 'png', 'word': 'aww'},
        {'dir': 'files1/', 'disppage': 5, 'pagenum': '555', 'sfx': 'png', 'word': 'am'},
        {'dir': 'files1/', 'disppage': 6, 'pagenum': '556', 'sfx': 'png', 'word': 'ard'},
        {'dir': 'files1/', 'disppage': 7, 'pagenum': '557', 'sfx': 'png', 'word': 'aS'},
        {'dir': 'files1/', 'disppage': 8, 'pagenum': '558', 'sfx': 'png', 'word': 'i'},
        {'dir': 'files1/', 'disppage': 9, 'pagenum': '559', 'sfx': 'png', 'word': 'iz'},
        {'dir': 'files1/', 'disppage': 10, 'pagenum': '560', 'sfx': 'png', 'word': 'Ir'},
        {'dir': 'files1/', 'disppage': 11, 'pagenum': '561', 'sfx': 'png', 'word': 'ucC'},
        {'dir': 'files1/', 'disppage': 12, 'pagenum': '562', 'sfx': 'png', 'word': 'Un'},
        {'dir': 'files1/', 'disppage': 13, 'pagenum': '563', 'sfx': 'png', 'word': 'fc'},
        {'dir': 'files1/', 'disppage': 14, 'pagenum': '564', 'sfx': 'png', 'word': 'F'},
        {'dir': 'files1/', 'disppage': 15, 'pagenum': '565', 'sfx': 'png', 'word': 'kak'},
        {'dir': 'files1/', 'disppage': 16, 'pagenum': '566', 'sfx': 'png', 'word': 'kaT'},
        {'dir': 'files1/', 'disppage': 17, 'pagenum': '567', 'sfx': 'png', 'word': 'kal'},
        {'dir': 'files1/', 'disppage': 18, 'pagenum': '568', 'sfx': 'png', 'word': 'kit'},
        {'dir': 'files1/', 'disppage': 19, 'pagenum': '569', 'sfx': 'png', 'word': 'kuR'},
        {'dir': 'files1/', 'disppage': 20, 'pagenum': '570', 'sfx': 'png', 'word': 'kuh\t\t\t\t'},
        {'dir': 'files1/', 'disppage': 21, 'pagenum': '571', 'sfx': 'png', 'word': 'kfS'},
        {'dir': 'files1/', 'disppage': 22, 'pagenum': '572', 'sfx': 'png', 'word': 'knaT'},
        {'dir': 'files1/', 'disppage': 23, 'pagenum': '573', 'sfx': 'png', 'word': 'kruS'},
        {'dir': 'files1/', 'disppage': 24, 'pagenum': '574', 'sfx': 'png', 'word': 'klIb'},
        {'dir': 'files1/', 'disppage': 25, 'pagenum': '575', 'sfx': 'png', 'word': 'kzam'},
        {'dir': 'files1/', 'disppage': 26, 'pagenum': '576', 'sfx': 'png', 'word': 'kzI'},
        {'dir': 'files1/', 'disppage': 27, 'pagenum': '577', 'sfx': 'png', 'word': 'kzE\t'},
        {'dir': 'files1/', 'disppage': 28, 'pagenum': '578', 'sfx': 'png', 'word': 'Kaw'},
        {'dir': 'files1/', 'disppage': 29, 'pagenum': '579', 'sfx': 'png', 'word': 'Kaz'},
        {'dir': 'files1/', 'disppage': 30, 'pagenum': '580', 'sfx': 'png', 'word': 'gaYj'},
        {'dir': 'files1/', 'disppage': 31, 'pagenum': '581', 'sfx': 'png', 'word': 'garv'},
        {'dir': 'files1/', 'disppage': 32, 'pagenum': '582', 'sfx': 'png', 'word': 'gu'},
        {'dir': 'files1/', 'disppage': 33, 'pagenum': '583', 'sfx': 'png', 'word': 'gup'},
        {'dir': 'files1/', 'disppage': 34, 'pagenum': '584', 'sfx': 'png', 'word': 'gfj'},
        {'dir': 'files1/', 'disppage': 35, 'pagenum': '585', 'sfx': 'png', 'word': 'granT'},
        {'dir': 'files1/', 'disppage': 36, 'pagenum': '586', 'sfx': 'png', 'word': 'glep'},
        {'dir': 'files1/', 'disppage': 37, 'pagenum': '587', 'sfx': 'png', 'word': 'Gu'},
        {'dir': 'files1/', 'disppage': 38, 'pagenum': '588', 'sfx': 'png', 'word': 'Gf'},
        {'dir': 'files1/', 'disppage': 39, 'pagenum': '589', 'sfx': 'png', 'word': 'cakz'},
        {'dir': 'files1/', 'disppage': 40, 'pagenum': '590', 'sfx': 'png', 'word': 'cap'},
        {'dir': 'files1/', 'disppage': 41, 'pagenum': '591', 'sfx': 'png', 'word': 'cal'},
        {'dir': 'files1/', 'disppage': 42, 'pagenum': '592', 'sfx': 'png', 'word': 'cil'},
        {'dir': 'files1/', 'disppage': 43, 'pagenum': '593', 'sfx': 'png', 'word': 'cumb'},
        {'dir': 'files1/', 'disppage': 44, 'pagenum': '594', 'sfx': 'png', 'word': 'Cad'},
        {'dir': 'files1/', 'disppage': 45, 'pagenum': '595', 'sfx': 'png', 'word': 'Ced'},
        {'dir': 'files1/', 'disppage': 46, 'pagenum': '596', 'sfx': 'png', 'word': 'jamB'},
        {'dir': 'files1/', 'disppage': 47, 'pagenum': '597', 'sfx': 'png', 'word': 'jim'},
        {'dir': 'files1/', 'disppage': 48, 'pagenum': '598', 'sfx': 'png', 'word': 'jF'},
        {'dir': 'files1/', 'disppage': 49, 'pagenum': '599', 'sfx': 'png', 'word': 'jvar'},
        {'dir': 'files1/', 'disppage': 50, 'pagenum': '600', 'sfx': 'png', 'word': 'wIk'},
        {'dir': 'files1/', 'disppage': 51, 'pagenum': '601', 'sfx': 'png', 'word': 'takz'},
        {'dir': 'files1/', 'disppage': 52, 'pagenum': '602', 'sfx': 'png', 'word': 'tap'},
        {'dir': 'files1/', 'disppage': 53, 'pagenum': '603', 'sfx': 'png', 'word': 'tik'},
        {'dir': 'files1/', 'disppage': 54, 'pagenum': '604', 'sfx': 'png', 'word': 'tu'},
        {'dir': 'files1/', 'disppage': 55, 'pagenum': '605', 'sfx': 'png', 'word': 'tump'},
        {'dir': 'files1/', 'disppage': 56, 'pagenum': '606', 'sfx': 'png', 'word': 'tfd'},
        {'dir': 'files1/', 'disppage': 57, 'pagenum': '607', 'sfx': 'png', 'word': 'tfMh'},
        {'dir': 'files1/', 'disppage': 58, 'pagenum': '608', 'sfx': 'png', 'word': 'tras'},
        {'dir': 'files1/', 'disppage': 59, 'pagenum': '609', 'sfx': 'png', 'word': 'tvaNg'},
        {'dir': 'files1/', 'disppage': 60, 'pagenum': '610', 'sfx': 'png', 'word': 'daG'},
        {'dir': 'files1/', 'disppage': 61, 'pagenum': '611', 'sfx': 'png', 'word': 'das'},
        {'dir': 'files1/', 'disppage': 62, 'pagenum': '612', 'sfx': 'png', 'word': 'div'},
        {'dir': 'files1/', 'disppage': 63, 'pagenum': '613', 'sfx': 'png', 'word': 'du'},
        {'dir': 'files1/', 'disppage': 64, 'pagenum': '614', 'sfx': 'png', 'word': 'dfp'},
        {'dir': 'files1/', 'disppage': 65, 'pagenum': '615', 'sfx': 'png', 'word': 'dev'},
        {'dir': 'files1/', 'disppage': 66, 'pagenum': '616', 'sfx': 'png', 'word': 'druR'},
        {'dir': 'files1/', 'disppage': 67, 'pagenum': '617', 'sfx': 'png', 'word': 'Danv'},
        {'dir': 'files1/', 'disppage': 68, 'pagenum': '618', 'sfx': 'png', 'word': 'DU'},
        {'dir': 'files1/', 'disppage': 69, 'pagenum': '619', 'sfx': 'png', 'word': 'Dfj,DfYj'},
        {'dir': 'files1/', 'disppage': 70, 'pagenum': '620', 'sfx': 'png', 'word': 'DraR'},
        {'dir': 'files1/', 'disppage': 71, 'pagenum': '621', 'sfx': 'png', 'word': 'Dvan'},
        {'dir': 'files1/', 'disppage': 72, 'pagenum': '622', 'sfx': 'png', 'word': 'nal'},
        {'dir': 'files1/', 'disppage': 73, 'pagenum': '623', 'sfx': 'png', 'word': 'nid'},
        {'dir': 'files1/', 'disppage': 74, 'pagenum': '624', 'sfx': 'png', 'word': 'nft'},
        {'dir': 'files1/', 'disppage': 75, 'pagenum': '625', 'sfx': 'png', 'word': 'paW'},
        {'dir': 'files1/', 'disppage': 76, 'pagenum': '626', 'sfx': 'png', 'word': 'pad'},
        {'dir': 'files1/', 'disppage': 77, 'pagenum': '627', 'sfx': 'png', 'word': 'pAl'},
        {'dir': 'files1/', 'disppage': 78, 'pagenum': '628', 'sfx': 'png', 'word': 'pis'},
        {'dir': 'files1/', 'disppage': 79, 'pagenum': '629', 'sfx': 'png', 'word': 'pur'},
        {'dir': 'files1/', 'disppage': 80, 'pagenum': '630', 'sfx': 'png', 'word': 'pUR'},
        {'dir': 'files1/', 'disppage': 81, 'pagenum': '631', 'sfx': 'png', 'word': 'pfYj'},
        {'dir': 'files1/', 'disppage': 82, 'pagenum': '632', 'sfx': 'png', 'word': 'praT'},
        {'dir': 'files1/', 'disppage': 83, 'pagenum': '633', 'sfx': 'png', 'word': 'proT'},
        {'dir': 'files1/', 'disppage': 84, 'pagenum': '634', 'sfx': 'png', 'word': 'Pul'},
        {'dir': 'files1/', 'disppage': 85, 'pagenum': '635', 'sfx': 'png', 'word': 'bal'},
        {'dir': 'files1/', 'disppage': 86, 'pagenum': '636', 'sfx': 'png', 'word': 'bust'},
        {'dir': 'files1/', 'disppage': 87, 'pagenum': '637', 'sfx': 'png', 'word': 'Baj'},
        {'dir': 'files1/', 'disppage': 88, 'pagenum': '638', 'sfx': 'png', 'word': 'Baz'},
        {'dir': 'files1/', 'disppage': 89, 'pagenum': '639', 'sfx': 'png', 'word': 'Buj'},
        {'dir': 'files1/', 'disppage': 90, 'pagenum': '640', 'sfx': 'png', 'word': 'Bf'},
        {'dir': 'files1/', 'disppage': 91, 'pagenum': '641', 'sfx': 'png', 'word': 'BraS'},
        {'dir': 'files1/', 'disppage': 92, 'pagenum': '642', 'sfx': 'png', 'word': 'BlAS'},
        {'dir': 'files1/', 'disppage': 93, 'pagenum': '643', 'sfx': 'png', 'word': 'maW'},
        {'dir': 'files1/', 'disppage': 94, 'pagenum': '644', 'sfx': 'png', 'word': 'man'},
        {'dir': 'files1/', 'disppage': 95, 'pagenum': '645', 'sfx': 'png', 'word': 'marv'},
        {'dir': 'files1/', 'disppage': 96, 'pagenum': '646', 'sfx': 'png', 'word': 'mA'},
        {'dir': 'files1/', 'disppage': 97, 'pagenum': '647', 'sfx': 'png', 'word': 'mid'},
        {'dir': 'files1/', 'disppage': 98, 'pagenum': '648', 'sfx': 'png', 'word': 'mI'},
        {'dir': 'files1/', 'disppage': 99, 'pagenum': '649', 'sfx': 'png', 'word': 'muRw'},
        {'dir': 'files1/', 'disppage': 100, 'pagenum': '650', 'sfx': 'png', 'word': 'mus'},
        {'dir': 'files1/', 'disppage': 101, 'pagenum': '651', 'sfx': 'png', 'word': 'mfkz'},
        {'dir': 'files1/', 'disppage': 102, 'pagenum': '652', 'sfx': 'png', 'word': 'mfS'},
        {'dir': 'files1/', 'disppage': 103, 'pagenum': '653', 'sfx': 'png', 'word': 'mnA'},
        {'dir': 'files1/', 'disppage': 104, 'pagenum': '654', 'sfx': 'png', 'word': 'mlO'},
        {'dir': 'files1/', 'disppage': 105, 'pagenum': '655', 'sfx': 'png', 'word': 'yam'},
        {'dir': 'files1/', 'disppage': 106, 'pagenum': '656', 'sfx': 'png', 'word': 'yuj'},
        {'dir': 'files1/', 'disppage': 107, 'pagenum': '657', 'sfx': 'png', 'word': 'rakz'},
        {'dir': 'files1/', 'disppage': 108, 'pagenum': '658', 'sfx': 'png', 'word': 'raD'},
        {'dir': 'files1/', 'disppage': 109, 'pagenum': '659', 'sfx': 'png', 'word': 'ras'},
        {'dir': 'files1/', 'disppage': 110, 'pagenum': '660', 'sfx': 'png', 'word': 'riK'},
        {'dir': 'files1/', 'disppage': 111, 'pagenum': '661', 'sfx': 'png', 'word': 'ru'},
        {'dir': 'files1/', 'disppage': 112, 'pagenum': '662', 'sfx': 'png', 'word': 'ruD'},
        {'dir': 'files1/', 'disppage': 113, 'pagenum': '663', 'sfx': 'png', 'word': 'rUz'},
        {'dir': 'files1/', 'disppage': 114, 'pagenum': '664', 'sfx': 'png', 'word': 'laNg'},
        {'dir': 'files1/', 'disppage': 115, 'pagenum': '665', 'sfx': 'png', 'word': 'lamb'},
        {'dir': 'files1/', 'disppage': 116, 'pagenum': '666', 'sfx': 'png', 'word': 'lAK'},
        {'dir': 'files1/', 'disppage': 117, 'pagenum': '667', 'sfx': 'png', 'word': 'lI'},
        {'dir': 'files1/', 'disppage': 118, 'pagenum': '668', 'sfx': 'png', 'word': 'lud'},
        {'dir': 'files1/', 'disppage': 119, 'pagenum': '669', 'sfx': 'png', 'word': 'lUz'},
        {'dir': 'files1/', 'disppage': 120, 'pagenum': '670', 'sfx': 'png', 'word': 'vac'},
        {'dir': 'files1/', 'disppage': 121, 'pagenum': '671', 'sfx': 'png', 'word': 'van'},
        {'dir': 'files1/', 'disppage': 122, 'pagenum': '672', 'sfx': 'png', 'word': 'val'},
        {'dir': 'files1/', 'disppage': 123, 'pagenum': '673', 'sfx': 'png', 'word': 'vah'},
        {'dir': 'files1/', 'disppage': 124, 'pagenum': '674', 'sfx': 'png', 'word': 'vicC'},
        {'dir': 'files1/', 'disppage': 125, 'pagenum': '675', 'sfx': 'png', 'word': 'viD '},
        {'dir': 'files1/', 'disppage': 126, 'pagenum': '676', 'sfx': 'png', 'word': 'vfj'},
        {'dir': 'files1/', 'disppage': 127, 'pagenum': '677', 'sfx': 'png', 'word': 'vfz'},
        {'dir': 'files1/', 'disppage': 128, 'pagenum': '678', 'sfx': 'png', 'word': 'vyac'},
        {'dir': 'files1/', 'disppage': 129, 'pagenum': '679', 'sfx': 'png', 'word': 'vrI'},
        {'dir': 'files1/', 'disppage': 130, 'pagenum': '680', 'sfx': 'png', 'word': 'SaW'},
        {'dir': 'files1/', 'disppage': 131, 'pagenum': '681', 'sfx': 'png', 'word': 'Saz'},
        {'dir': 'files1/', 'disppage': 132, 'pagenum': '682', 'sfx': 'png', 'word': 'Siz'},
        {'dir': 'files1/', 'disppage': 133, 'pagenum': '683', 'sfx': 'png', 'word': 'SuW'},
        {'dir': 'files1/', 'disppage': 134, 'pagenum': '684', 'sfx': 'png', 'word': 'SUr'},
        {'dir': 'files1/', 'disppage': 135, 'pagenum': '685', 'sfx': 'png', 'word': 'Scyut'},
        {'dir': 'files1/', 'disppage': 136, 'pagenum': '686', 'sfx': 'png', 'word': 'Sri'},
        {'dir': 'files1/', 'disppage': 137, 'pagenum': '687', 'sfx': 'png', 'word': 'Slok'},
        {'dir': 'files1/', 'disppage': 138, 'pagenum': '688', 'sfx': 'png', 'word': 'Svind'},
        {'dir': 'files1/', 'disppage': 139, 'pagenum': '689', 'sfx': 'png', 'word': 'satr'},
        {'dir': 'files1/', 'disppage': 140, 'pagenum': '690', 'sfx': 'png', 'word': 'sarv'},
        {'dir': 'files1/', 'disppage': 141, 'pagenum': '691', 'sfx': 'png', 'word': 'siw'},
        {'dir': 'files1/', 'disppage': 142, 'pagenum': '692', 'sfx': 'png', 'word': 'suK'},
        {'dir': 'files1/', 'disppage': 143, 'pagenum': '693', 'sfx': 'png', 'word': 'sfj'},
        {'dir': 'files1/', 'disppage': 144, 'pagenum': '694', 'sfx': 'png', 'word': 'skund'},
        {'dir': 'files1/', 'disppage': 145, 'pagenum': '695', 'sfx': 'png', 'word': 'stu'},
        {'dir': 'files1/', 'disppage': 146, 'pagenum': '696', 'sfx': 'png', 'word': 'sTag'},
        {'dir': 'files1/', 'disppage': 147, 'pagenum': '697', 'sfx': 'png', 'word': 'snE'},
        {'dir': 'files1/', 'disppage': 148, 'pagenum': '698', 'sfx': 'png', 'word': 'sPuw'},
        {'dir': 'files1/', 'disppage': 149, 'pagenum': '699', 'sfx': 'png', 'word': 'smf'},
        {'dir': 'files1/', 'disppage': 150, 'pagenum': '700', 'sfx': 'png', 'word': 'sru'},
        {'dir': 'files1/', 'disppage': 151, 'pagenum': '701', 'sfx': 'png', 'word': 'svask'},
        {'dir': 'files1/', 'disppage': 152, 'pagenum': '702', 'sfx': 'png', 'word': 'hamm'},
        {'dir': 'files1/', 'disppage': 153, 'pagenum': '703', 'sfx': 'png', 'word': 'hikk'},
        {'dir': 'files1/', 'disppage': 154, 'pagenum': '704', 'sfx': 'png', 'word': 'hf'},
        {'dir': 'files1/', 'disppage': 155, 'pagenum': '705', 'sfx': 'png', 'word': 'hrag'},
        {'dir': 'files1/', 'disppage': 156, 'pagenum': '706', 'sfx': 'png', 'word': 'hlAd(end of Dhatukosha)'}],
 'PR': [{'dir': 'files1/', 'disppage': 1, 'pagenum': '710', 'sfx': 'png', 'word': 'Appendix I: Prosody'},
        {'dir': 'files1/', 'disppage': 2, 'pagenum': '711', 'sfx': 'png', 'word': 'Introduction, 2'},
        {'dir': 'files1/', 'disppage': 3, 'pagenum': '712', 'sfx': 'png', 'word': '&sect; I. <span class="san">samavftta</span>'},
        {'dir': 'files1/', 'disppage': 4, 'pagenum': '713', 'sfx': 'png', 'word': '8 syllables'},
        {'dir': 'files1/', 'disppage': 5, 'pagenum': '714', 'sfx': 'png', 'word': '9,10 syllables'},
        {'dir': 'files1/', 'disppage': 6, 'pagenum': '715', 'sfx': 'png', 'word': '11 syllables'},
        {'dir': 'files1/', 'disppage': 7, 'pagenum': '716', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 8, 'pagenum': '717', 'sfx': 'png', 'word': '12 syllables'},
        {'dir': 'files1/', 'disppage': 9, 'pagenum': '718', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 10, 'pagenum': '719', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 11, 'pagenum': '720', 'sfx': 'png', 'word': '13 syllables'},
        {'dir': 'files1/', 'disppage': 12, 'pagenum': '721', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 13, 'pagenum': '722', 'sfx': 'png', 'word': '14 syllables'},
        {'dir': 'files1/', 'disppage': 14, 'pagenum': '723', 'sfx': 'png', 'word': '15 syllables'},
        {'dir': 'files1/', 'disppage': 15, 'pagenum': '724', 'sfx': 'png', 'word': '16 syllables'},
        {'dir': 'files1/', 'disppage': 16, 'pagenum': '725', 'sfx': 'png', 'word': '17 syllables'},
        {'dir': 'files1/', 'disppage': 17, 'pagenum': '726', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 18, 'pagenum': '727', 'sfx': 'png', 'word': '18 syllables'},
        {'dir': 'files1/', 'disppage': 19, 'pagenum': '728', 'sfx': 'png', 'word': '19 syllables'},
        {'dir': 'files1/', 'disppage': 20, 'pagenum': '729', 'sfx': 'png', 'word': '20,21 syllables'},
        {'dir': 'files1/', 'disppage': 21, 'pagenum': '730', 'sfx': 'png', 'word': '22 syllables'},
        {'dir': 'files1/', 'disppage': 22, 'pagenum': '731', 'sfx': 'png', 'word': '&sect; II. <span class="san">arDasamavftta</span>'},
        {'dir': 'files1/', 'disppage': 23, 'pagenum': '732', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 24, 'pagenum': '733', 'sfx': 'png', 'word': '&sect; III. <span class="san">vizamavftta</span>'},
        {'dir': 'files1/', 'disppage': 25, 'pagenum': '734', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 26, 'pagenum': '735', 'sfx': 'png', 'word': ''},
        {'dir': 'files1/', 'disppage': 27, 'pagenum': '736', 'sfx': 'png', 'word': '(end of Prosody)'}]};
