filetop = [
{  'dir':'files1/',  'sfx':'png',  'filename':'kale00.txt',  'word':'Preliminary material',  'pagenum':'005',  'disppage':'',  'code':'00',  }, 
{  'dir':'files1/',  'sfx':'png',  'filename':'kale01.txt',  'word':'I. Alphabet',  'pagenum':'015',  'disppage':'1',  'code':'01',  }, 
{  'dir':'files1/',  'sfx':'png',  'filename':'kale02.txt',  'word':'II. Rules of Sandhi',  'pagenum':'026',  'disppage':'12',  'code':'02',  }, 
{  'dir':'files1/',  'sfx':'png',  'filename':'kale03.txt',  'word':'III. Declension of nouns',  'pagenum':'046',  'disppage':'32',  'code':'03',  }, 
{  'dir':'files1/',  'sfx':'png',  'filename':'kale04.txt',  'word':'IV. Pronouns and their Declension',  'pagenum':'101',  'disppage':'87',  'code':'04',  }, 
{  'dir':'files1/',  'sfx':'png',  'filename':'kale05.txt',  'word':'V. Numerals and their Declension',  'pagenum':'116',  'disppage':'102',  'code':'05',  }, 
{  'dir':'files1/',  'sfx':'png',  'filename':'kale06.txt',  'word':'VI. Degree of Comparison',  'pagenum':'124',  'disppage':'110',  'code':'06',  }, 
{  'dir':'files1/',  'sfx':'png',  'filename':'kale07.txt',  'word':'VII. Compounds',  'pagenum':'127',  'disppage':'113',  'code':'07',  }, 
{  'dir':'files1/',  'sfx':'png',  'filename':'kale08.txt',  'word':'VIII. Formation of Feminine Bases',  'pagenum':'194',  'disppage':'180',  'code':'08',  }, 
{  'dir':'files1/',  'sfx':'png',  'filename':'kale09.txt',  'word':'IX. Secondary Nominal Bases',  'pagenum':'208',  'disppage':'194',  'code':'09',  }, 
{  'dir':'files1/',  'sfx':'png',  'filename':'kale10.txt',  'word':'X. Gender',  'pagenum':'230',  'disppage':'216',  'code':'10',  }, 
{  'dir':'files1/',  'sfx':'png',  'filename':'kale11.txt',  'word':'XI. Avyayas or Indeclinables',  'pagenum':'237',  'disppage':'223',  'code':'11',  }, 
{  'dir':'files1/',  'sfx':'png',  'filename':'kale12.txt',  'word':'XII. Conjugation of Verbs',  'pagenum':'252',  'disppage':'238',  'code':'12',  }, 
{  'dir':'files1/',  'sfx':'png',  'filename':'kale13.txt',  'word':'XIII. Parasmaipada / Atmanepada',  'pagenum':'413',  'disppage':'399',  'code':'13',  }, 
{  'dir':'files1/',  'sfx':'png',  'filename':'kale14.txt',  'word':'XIV. Verbal Derivatives',  'pagenum':'430',  'disppage':'416',  'code':'14',  }, 
{  'dir':'files1/',  'sfx':'png',  'filename':'kale15.txt',  'word':'XV. Syntax',  'pagenum':'482',  'disppage':'468',  'code':'15',  }, 
{  'dir':'files1/',  'sfx':'png',  'filename':'kaleDK.txt',  'word':'Appendix II: Dhatukosha',  'pagenum':'551',  'disppage':'1',  'code':'DK',  }, 
{  'dir':'files1/',  'sfx':'png',  'filename':'kalePR.txt',  'word':'Appendix I: Prosody',  'pagenum':'710',  'disppage':'1',  'code':'PR',  }, 
];
